/* Generated By:JJTree: Do not edit this line. ASTEmptyFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.apache.commons.jexl3.parser;

public
class ASTEmptyFunction extends JexlNode {
  public ASTEmptyFunction(int id) {
    super(id);
  }

  public ASTEmptyFunction(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3dfeccd3d7dd9e1cfef9bad520b974d1 (do not edit this line) */
