/* Generated By:JJTree: Do not edit this line. ASTBitwiseAndNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.apache.commons.jexl3.parser;

public
class ASTBitwiseAndNode extends JexlNode {
  public ASTBitwiseAndNode(int id) {
    super(id);
  }

  public ASTBitwiseAndNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2d9d5295ac6b579d006ec0fbe02b2d1d (do not edit this line) */
