/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.apache.commons.jexl3.parser;

public
class ASTBitwiseXorNode extends JexlNode {
  public ASTBitwiseXorNode(int id) {
    super(id);
  }

  public ASTBitwiseXorNode(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9561b743a26e88b90482aece393bd2a8 (do not edit this line) */
