/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package org.apache.commons.jexl3.parser;

public interface ParserTreeConstants
{
  public int JJTJEXLSCRIPT = 0;
  public int JJTANNOTATION = 1;
  public int JJTANNOTATEDSTATEMENT = 2;
  public int JJTVOID = 3;
  public int JJTBLOCK = 4;
  public int JJTAMBIGUOUS = 5;
  public int JJTIFSTATEMENT = 6;
  public int JJTWHILESTATEMENT = 7;
  public int JJTRETURNSTATEMENT = 8;
  public int JJTCONTINUE = 9;
  public int JJTBREAK = 10;
  public int JJTFOREACHSTATEMENT = 11;
  public int JJTREFERENCE = 12;
  public int JJTASSIGNMENT = 13;
  public int JJTVAR = 14;
  public int JJTSETADDNODE = 15;
  public int JJTSETMULTNODE = 16;
  public int JJTSETDIVNODE = 17;
  public int JJTSETMODNODE = 18;
  public int JJTSETANDNODE = 19;
  public int JJTSETORNODE = 20;
  public int JJTSETXORNODE = 21;
  public int JJTSETSUBNODE = 22;
  public int JJTTERNARYNODE = 23;
  public int JJTORNODE = 24;
  public int JJTANDNODE = 25;
  public int JJTBITWISEORNODE = 26;
  public int JJTBITWISEXORNODE = 27;
  public int JJTBITWISEANDNODE = 28;
  public int JJTEQNODE = 29;
  public int JJTNENODE = 30;
  public int JJTRANGENODE = 31;
  public int JJTLTNODE = 32;
  public int JJTGTNODE = 33;
  public int JJTLENODE = 34;
  public int JJTGENODE = 35;
  public int JJTERNODE = 36;
  public int JJTNRNODE = 37;
  public int JJTSWNODE = 38;
  public int JJTNSWNODE = 39;
  public int JJTEWNODE = 40;
  public int JJTNEWNODE = 41;
  public int JJTADDNODE = 42;
  public int JJTSUBNODE = 43;
  public int JJTMULNODE = 44;
  public int JJTDIVNODE = 45;
  public int JJTMODNODE = 46;
  public int JJTUNARYMINUSNODE = 47;
  public int JJTBITWISECOMPLNODE = 48;
  public int JJTNOTNODE = 49;
  public int JJTEMPTYFUNCTION = 50;
  public int JJTSIZEFUNCTION = 51;
  public int JJTIDENTIFIER = 52;
  public int JJTNUMBERLITERAL = 53;
  public int JJTNULLLITERAL = 54;
  public int JJTTRUENODE = 55;
  public int JJTFALSENODE = 56;
  public int JJTSTRINGLITERAL = 57;
  public int JJTJXLTLITERAL = 58;
  public int JJTEXTENDEDLITERAL = 59;
  public int JJTARRAYLITERAL = 60;
  public int JJTMAPLITERAL = 61;
  public int JJTMAPENTRY = 62;
  public int JJTSETLITERAL = 63;
  public int JJTEMPTYMETHOD = 64;
  public int JJTSIZEMETHOD = 65;
  public int JJTARGUMENTS = 66;
  public int JJTFUNCTIONNODE = 67;
  public int JJTCONSTRUCTORNODE = 68;
  public int JJTJEXLLAMBDA = 69;
  public int JJTIDENTIFIERACCESS = 70;
  public int JJTARRAYACCESS = 71;
  public int JJTMETHODNODE = 72;
  public int JJTREFERENCEEXPRESSION = 73;


  public String[] jjtNodeName = {
    "JexlScript",
    "Annotation",
    "AnnotatedStatement",
    "void",
    "Block",
    "Ambiguous",
    "IfStatement",
    "WhileStatement",
    "ReturnStatement",
    "Continue",
    "Break",
    "ForeachStatement",
    "Reference",
    "Assignment",
    "Var",
    "SetAddNode",
    "SetMultNode",
    "SetDivNode",
    "SetModNode",
    "SetAndNode",
    "SetOrNode",
    "SetXorNode",
    "SetSubNode",
    "TernaryNode",
    "OrNode",
    "AndNode",
    "BitwiseOrNode",
    "BitwiseXorNode",
    "BitwiseAndNode",
    "EQNode",
    "NENode",
    "RangeNode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "ERNode",
    "NRNode",
    "SWNode",
    "NSWNode",
    "EWNode",
    "NEWNode",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "UnaryMinusNode",
    "BitwiseComplNode",
    "NotNode",
    "EmptyFunction",
    "SizeFunction",
    "Identifier",
    "NumberLiteral",
    "NullLiteral",
    "TrueNode",
    "FalseNode",
    "StringLiteral",
    "JxltLiteral",
    "ExtendedLiteral",
    "ArrayLiteral",
    "MapLiteral",
    "MapEntry",
    "SetLiteral",
    "EmptyMethod",
    "SizeMethod",
    "Arguments",
    "FunctionNode",
    "ConstructorNode",
    "JexlLambda",
    "IdentifierAccess",
    "ArrayAccess",
    "MethodNode",
    "ReferenceExpression",
  };
}
/* JavaCC - OriginalChecksum=cd3994c504cbec2f221508f738e85566 (do not edit this line) */
